# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - never stale
# Label to use when marking an issue as stale
staleLabel: timed out
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity in the last 180 days. It will be closed if no further
  activity occurs in the next week. Please feel free to comment if you'd like
  it to remain open, and thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it has not had recent
  activity. You may re-open the issue if it is still relevant.
