name: Audit

on:
  push:
  pull_request:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/audit.toml"
      - "**/package-lock.json"
      - "**/npm-shrinkwrap.json"
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: npm audit
        uses: oke-py/npm-audit-action@v1.7.3
        with:
          dedupe_issues: true
          working_directory: npm
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: changelog-generator audit
        uses: oke-py/npm-audit-action@v1.7.3
        with:
          dedupe_issues: true
          working_directory: changelog-generator
          github_token: ${{ secrets.GITHUB_TOKEN }}
